optimizer:
  name: adam
  learning_rate: 0.001

scheduler:
  name: step_lr
  step_size: 10
  gamma: 0.1

loss:
  name: gdp_mse

path:
  input: C:\Users\sx119\Desktop\GaussianDenoisingPosterior\Data
  output: C:\Users\sx119\Desktop\GaussianDenoisingPosterior\outputs\deblurring

hyperparameter:
  epochs: 20
  train_batch: 32
  vali_batch: 4
  train_crop: 128
  vali_crop: 1024
