optimizer:
  name: adam
  learning_rate: 0.001

scheduler:
  name: step_lr
  step_size: 10
  gamma: 0.1

loss:
  name: mse

path:
  input: C:\Users\sx119\Desktop\gdp_data
  output: C:\Users\sx119\Desktop\GaussianDenoisingPosterior\outputs\deblurring

hyperparameter:
  epochs: 20
  train_batch: 56
  vali_batch: 1
  train_crop: 128
  vali_crop: 1024

num_workers:
  num: 2

noise_level:
  start: 15
  end: 15

net_mode:
  mode: "d"