optimizer:
  name: adam
  learning_rate: 0.001

scheduler:
  name: step_lr
  step_size: 10
  gamma: 0.1

loss:
  name: mse

path:
  input: C:\Users\sx119\Desktop\gdp_data
  output: C:\Users\sx119\Desktop\GaussianDenoisingPosterior\outputs\deblurring

hyperparameter:
  epochs: 40
  train_batch: 72
  vali_batch: 16

num_workers:
  num: 4

noise_level:
  start: 15
  end: 15

net_mode:
  mode: "d"