optimizer:
  name: adam
  learning_rate: 0.001

scheduler:
  name: step_lr
  step_size: 10
  gamma: 0.5

loss:
  name: mse

path:
  input: data/ffhq256
  output: outputs/deblurring

hyperparameter:
  epochs: 40
  train_batch: 16
  vali_batch: 16

num_workers:
  num: 4


net:
  name: "DnCNN"

seed:
  number: 42