optimizer:
  name: adam
  learning_rate: 0.001

scheduler:
  name: step_lr
  step_size: 10
  gamma: 0.5

loss:
  name: mse

path:
  input: data/ffhq256
  output: outputs/deblurring

hyperparameter:
  epochs: 40
  train_batch: 16
  vali_batch: 4

num_workers:
  num: 0

net:
  name: "UNet" # DnCNN or UNet

seed:
  number: 42

subproblem: # SR(super resolution), IP(inpaint)
  name: "IP"

server: # YES - on server, NO, local
  status: "NO"

augmentation: "NO"